var runner = TestRunner()

await PermissionTests.run(&runner)
await ASRProviderTests.run(&runner)
await RecognitionSessionTests.run(&runner)
await CapsuleAnimationTests.run(&runner)
await AppSettingsNotificationTests.run(&runner)
await RecordingStateMachineTests.run(&runner)
await KeychainTests.run(&runner)
await AudioRouterTests.run(&runner)
await RecognitionFinalizerTests.run(&runner)
await PunctuationTests.run(&runner)
await UpdateCheckerTests.run(&runner)
await LLMRefinerTests.run(&runner)
await HeadphoneHIDTests.run(&runner)
await SherpaPreloadTests.run(&runner)

runner.finish()
